##
## Configurações globais do site:
## 

# Título do site:
title: CR6.100B - adaptação da Harvard CS50 para os alunos brasileiros!

# E-mail do responsável:
email: abrantesasf@uvv.br

# Descrição (">-" ignora os newlines):
description: >-
  Disciplina de introdução à Ciência da Computação, para estudantes brasileiros,
  adaptada da disciplina Harvard CS50x.

# URL padrão do site
url: "https://www.cc1n.com.br" # URL padrão do site

# O site começa em um subpath da URL, por exemplo, /blog? se o site começa
# na URL padrão, deixe em branco.
baseurl: ""

# Linguagem padrão para o conteúdo do site:
lang: "pt-br"

# Google Analytics
#ga_tracking: ""

# Redes sociais:
twitter_username: "computacaoraiz"
github_username: "computacaoraiz"


##
## Configurações para o tema:
##
cs50:
  title: CR6.100B - Introdução à Ciência da Computação
  locale: pt-BR
  tz: America/Sao_Paulo
  description: Disciplina de introdução à Ciência da Computação, para estudantes brasileiros, adaptada da Harvard CS50x.
  alert: warning dismissible


##
## Coleções para os dados do site
##



##
## Configurações para o build:
##

# Compressão de HTML:
compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false
  profile: false

# Plugins a serem utilizados:
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Engine de processamento:
kramdown:
  input: Kramdown
  syntax_highlighter: coderay

# O que excluir do build (se diretório, usar a / final):
exclude:
  - Gemfile
  - Gemfile.lock
  - _config.yml
